wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694827162.430989
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 23
      4: 3.10.12
      5: 0.15.10
      8:
      - 5
